#!/bin/bash
Welcome()
{
 reset
	echo  -e "\t\t\t\t \e[1;46m   欢迎来到疫情小常识系统-版本0.3   \e[0m"
	echo  -e "\n\n\n\n\n\n\n\n\n\n\t\t\t\t\t\e[1;31m Enter 进入疫情管理系统\e[0m"
	read -t 5
Main_menu
}

quit()
{
	clear
	echo  -e "\t\t\t\t \e[1;46m  疫情小常识版本0.1   \e[0m"
	echo  -e "\n\n\n\n\n\n\n\n\n\n\t\t\t\t\t\e[1;32m EXIT 疫情管理系统\e[2m"
	echo  -e "\n\n\n\n\n\n\t\t\t\t\t\e[1;31m   谢谢您的使用\e[0m"
	read  -t 2

	exit 0

}
Main_menu(){
	clear
echo  -e  "\t\t\t\t\t\e[1;29m| 1.添加"
echo  -e  "\t\t\t\t\t| 2.删除"
echo  -e  "\t\t\t\t\t| 3.BMI"
echo  -e  "\t\t\t\t\t| 4.其他"
echo  -e  "\t\t\t\t\t\e[1;29m| q.退出系统\e[0m"
echo  -e  "\e[1;31m---------------\e[0m"
read  -p  "请您选择：" choice

case $choice in
	"1") add ;;
	"2") delete ;;
	"3") bmi ;;
	"4") list ;;
	"q") quit ;;
	*) Main_menu ;;

esac
}
add(){
echo "请输入要创建或修改的文件名称"
read f
	if [ ! -d $f ];then
		mkdir -p $f/
		
	else
	echo "请输入要编辑的文件内容,或输入quit返回主页"
	read a
		while [ "$a" = '' ];do
		read -p  "输入的文件夹不能空，请重新输入:" a	
		done
		while [ "$a" = 'quit' ];do
		case $a  in
		
	quit)		
	Main_menu	 ;;
	esac
		done
		if [ ! -f $a ];then
		touch $a.txt 
		mv $a.txt ./$f
	fi
	fi
	clear
 echo -e  "\n\n\t\t\t\t\e[1;31m       创建成功\e[0m\n\n\n"
	 echo -e "返回主目录:0   继续添加:1  查看好东西:2  退出系统:q \n" 
  echo  -e  "\e[1;31m---------------\e[0m"
  read -p "请您选择：" choice
  case $choice  in
  	0)
  		Main_menu	  ;;
  	1) 
  		add 	  ;;
	2)
  	    	list	  ;;
	3)   
		bmi	;;
  		
  	q)
		clear
  		quit  	  ;;
  	*)
		Main_menu 	  ;;
  esac
}

delete(){
	echo "请输入要删除的文件"
	read  p
	if [ -f $p ]; then     
		
  		rm $p
	else 
		  echo -e "\n\e[1;35m 路径不存在 \e[0m \n\n"
            echo -e "\t返回主目录:0   重新删除:1  退出:q \n"  
                read -p "请您选择：" choice
                        case $choice  in
                                0)
                                        Main_menu        ;;
                                1)
                                        delete      ;;
                                q) 
                                        clear
                                        quit     ;;
                                *)
                                        Main_menu        ;;
                         esac

 	fi
}

list(){
	clear
	cat ./test/epidemic.txt
	read -p "请您选择：echo -e \t返回主目录:0  退出:q \n"  choice
                        case $choice  in
                                0)
                                        Main_menu        ;;
                                q)
                                        clear
                                        quit     ;;
                                *)
                                        Main_menu        ;;
                         esac
		
}

bmi(){
	clear	
	read -p "请输入身高(m为单位): " h
	while [[ ! "$h" =~ [0-2].?[0-9]{,2}$ ]];do
	echo "请输入正确的身高"
	read -p	"身高：" h
	
	done
	read -p "请输入您的体重(kg):" w
	while [[ ! "$w" =~ [0-9]{1,3}$ ]];do
	echo "请输入正确的体重"
	read -p "体重" w

	done
	bmi=`echo $w/$h^2 | bc`
	echo "bmi: $bmi"
if [ $bmi -le 18 ] ;then
echo "太瘦了,跟猴子一样"
elif  [  $bmi -gt 24 ];then
echo "太胖了,和河马一样"
else
echo "标准"
fi

	 read -p "请您选择：echo -e \t返回主目录:0  再测一次:1  退出:q \n"  choice
                        case $choice  in
                                0)
                                        Main_menu        ;;
				1)
					bmi
							;;
                                q)
                                        clear
                                        quit     ;;
                                *)
                                        Main_menu        ;;
                         esac	
}
Welcome
